name: Update RPM Repository

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Create RPM Database
        run: |
          # Create repo file structure on gh-pages branch
          git fetch origin
          git checkout --orphan gh-pages
          git rm -rf .
          git checkout master -- Packages RPM-GPG-KEY

          # Create repo metadata
          sudo apt-get update
          sudo apt-get install createrepo-c
          createrepo_c .
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2